basePath: /v1
definitions:
  dto.CreateUserRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dto.LoginUserRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: api.midpoint.place
info:
  contact: {}
  description: This is the API for the Midpoint Place project
  title: Midpoint Place API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Register a new user
      operationId: register-user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses: {}
      summary: Register a new user
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      description: Login a user
      operationId: login-user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.LoginUserRequest'
      produces:
      - application/json
      responses: {}
      summary: Login a user
      tags:
      - users
schemes:
- http
- https
swagger: "2.0"
